[[plugins]]
  package = '@netlify/plugin-sitemap'

	[plugins.inputs]
	buildDir = "."
	filePath = "sitemap-netlify.xml"
					
[build]
	publish = "dist"

[functions]
  node_bundler = "esbuild"
	included_files = ["./public/data/dictionary_server.json", "./public/data/theater.json", "./public/data/antrepriza.ldb"]
