[[plugins]]
  package = '@netlify/plugin-sitemap'

	[plugins.inputs]
	buildDir = "."
	filePath = "sitemap-netlify.xml"
					
[build]
	publish = "dist"

[functions]
  node_bundler = "esbuild"
	included_files = []

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200